apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommender-api
  template:
    metadata:
      labels:
        app: recommender-api
    spec:
      containers:
        - name: recommender-container
          image: your-dockerhub-username/recommender-api:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
