name: CI-CD
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install fastapi uvicorn[standard] pickle5 scipy
      - name: Build Docker image
        run: docker build -t recommender-api ./api
      - name: Deploy container (placeholder)
        run: echo "Deploy to ECS/GCP step here"
