name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_S_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ecommerce-recommender-464115
          install_components: 'beta'
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scipy numpy scikit-learn implicit mlflow

      - name: Run model training
        run: |
          python model/train_model.py
    
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/ecommerce-recommender-464115/ecommerce-recommender-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ecommerce-recommender-api \
            --image gcr.io/ecommerce-recommender-464115/ecommerce-recommender-api \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated


